local b = {
	name = "base21",
	png64 = "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAQAAAADHm0dAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAUUlEQVQoz9WTQQ4AIQgDO/7/z3owG6OYQA97kCNMCoGCQvQuSXDmidBW5oJG7MTJwAWTgx/cVA4qmlPXUHUGqLU3VZ/awF+HtZxl+dX6gvy3BqfbGhye2M9tAAAAAElFTkSuQmCC"
}
